services:
  php:
    build:
      context: ./php
      dockerfile: ./php.Dockerfile
      args:
        USER: #leave it empty to use your current user
        UID: ${UID:-1000} # https://docs.docker.com/compose/compose-file/#variable-substitution
        TIME_ZONE: ${TIME_ZONE:-Asia/Ho_Chi_Minh}
        PHP_VER: 8
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-debug}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./public_html/:/var/www/html/
  nodejs:
    build:
      context: ./nodejs
      args:
        UID: ${UID:-1000}
    volumes:
      - ./public_html/:/var/www/html/
    entrypoint: ["tail", "-f", "/dev/null"]
  elasticsearch:
    image: elasticsearch:7.17.20
    volumes:
      - ./search_engine/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
  opensearch:
    image: opensearchproject/opensearch:latest
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
    volumes:
      - ./search_engine/opensearch/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
      - opensearch_data:/usr/share/opensearch/data
  httpd:
    build:
      context: ./httpd
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf/docker:ro
      - ./httpd/logs:/usr/local/apache2/logs
      - ./httpd/certs:/usr/local/apache2/certs:ro
      - ./public_html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/volumes/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "1"
    ports:
      - "3306:3306"
  mariadb:
    image: mariadb:10.6
    volumes:
      - ./database/volumes/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "1"
    ports:
      - "3306:3306"
  mailpit:
    image: axllent/mailpit
    volumes:
      - mailpit_data:/data
    ports:
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 500
      MP_DATABASE: /data/mailpit.db
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - ./database/volumes/postgres/17/data:/var/lib/postgresql/data

volumes:
  elasticsearch_data:
  opensearch_data:
  mailpit_data: