version: '3'

services:
  php:
    build:
      context: ./php
      dockerfile: ./php.Dockerfile
      args:
        USER: #leave it empty to use your current user
        UID: ${UID:-1000} # https://docs.docker.com/compose/compose-file/#variable-substitution
        TIME_ZONE: ${TIME_ZONE:-Asia/Ho_Chi_Minh}
        PHP_VER: ${PHP_VER:-7.3}
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    container_name: php73
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      - docker-lamp
  php74:
    extends:
      service: php
    build:
      args:
        PHP_VER: 7.4
    container_name: php74
  nodejs:
    build:
      context: ./nodejs
      args:
        UID: ${UID:-1000}
    volumes:
      - ./public_html/:/var/www/html/
    entrypoint: ["tail", "-f", "/dev/null"]
  httpd:
    build:
      context: ./httpd
    container_name: httpd
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf/docker:ro
      - ./httpd/logs:/usr/local/apache2/logs
      - ./public_html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker-lamp
  mariadb:
    image: mariadb:10.4
    container_name: maziadb
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "1"
    networks:
      docker-lamp:
        ipv4_address: 10.5.0.100
  elasticsearch:
    image: elasticsearch:7.17.2
    container_name: elasticsearch
    volumes:
      - './elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro'
      - 'esdata:/usr/share/elasticsearch/data'
    environment:
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
    networks:
      - docker-lamp

volumes:
  esdata:

networks:
  docker-lamp:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
