version: '2'

services:
  php:
    build:
      context: ./php
      args:
        USER_NAME: 'chung'
        UID: '1000'
    container_name: php71
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      docker-lamp:
  php72:
    extends:
      service: php
    build:
      dockerfile: ./php72.Dockerfile
    container_name: php72
#  php70:
#    extends:
#      service: php
#    build:
#      dockerfile: ./php70.Dockerfile
#    container_name: php70
  # php56:
    # extends:
      # service: php
    # build:
      # dockerfile: ./php56.Dockerfile
    # container_name: php56
  httpd:
    build:
      context: ./httpd
    container_name: httpd
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf/docker
      - ./public_html/:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    networks:
      docker-lamp:
  mariadb:
    image: mariadb:10.4
    container_name: maziadb
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "1"
    #ports:
    #  - "3306:3306"
    networks:
      docker-lamp:
        ipv4_address: 10.5.0.100
#  nodejs:
#    build:
#      context: ./nodejs
#    container_name: nodejs
#    volumes:
#      - ./public_html/:/var/www/html/
#    networks:
#      docker-lamp:
#  mongodb:
#    image: mongo:4.0
#    container_name: mongodb
#    entrypoint: ["echo", "Service disabled."]
#    volumes:
#      - ./mongodb/data:/data/db
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: 1
#    #ports:
#    #  - "27017:27017"
#    networks:
#      docker-lamp:
networks:
  docker-lamp:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
