version: '2.1'

services:
  php:
    build:
      context: ./php
      dockerfile: ./php73.Dockerfile
      args:
        USER: #leave it empty to use your current user
        UID: "${UID:-1000}"
        TIME_ZONE: 'Asia/Ho_Chi_Minh'
    container_name: php73
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      docker-lamp:
  php71:
    extends:
      service: php
    build:
      dockerfile: ./php71.Dockerfile
    container_name: php71
  httpd:
    build:
      context: ./httpd
    container_name: httpd
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf/docker:ro
      - ./httpd/logs:/usr/local/apache2/logs
      - ./public_html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      docker-lamp:
  mariadb:
    image: mariadb:10.4
    container_name: maziadb
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "1"
    networks:
      docker-lamp:
        ipv4_address: 10.5.0.100
networks:
  docker-lamp:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
