version: '2'

services:
  php:
    build:
      context: ./php
      dockerfile: ./php73.Dockerfile
      args:
        USER_NAME: 'chung'
        UID: '1000'
        TIME_ZONE: 'Asia/Ho_Chi_Minh'
    container_name: php73
    volumes:
      - ./public_html/:/var/www/html/
    networks:
      docker-lamp:
  php74:
    extends:
      service: php
    build:
      dockerfile: ./php74.Dockerfile
    container_name: php74
  httpd:
    build:
      context: ./httpd
    container_name: httpd
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf/docker
      - ./public_html/:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    networks:
      docker-lamp:
  mariadb:
    image: mariadb:10.4
    container_name: maziadb
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "1"
    networks:
      docker-lamp:
        ipv4_address: 10.5.0.100
networks:
  docker-lamp:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
