version: '2'

services:
  php-apache:
    build:
      context: ./php-apache
      args:
        USER_NAME: 'chung'
        UID: '1000'
    container_name: php71
    restart: always
    volumes:
      - ./public_html/:/var/www/html/
      - ./php-apache/apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./php-apache/apache2/sites-available:/etc/apache2/sites-available
      - ./php-apache/apache2/sites-enabled:/etc/apache2/sites-enabled
      - ./php-apache/php/conf.d/php.ini:/usr/local/etc/php/conf.d/zz-php.ini
    ports:
      - "80:80"
    networks:
      static-ip:
        ipv4_address: 10.5.0.5
    links: 
      - 'mariadb'
  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    expose:
      - "3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "no"
        MYSQL_ROOT_PASSWORD: "1"
    ports:
      - 3306:3306
    networks:
      static-ip:
        ipv4_address: 10.5.0.6
networks:
  static-ip:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
volumes:
    mariadb:
