version: '3'

services:
  php:
    build:
      context: ./php
      dockerfile: ./php.Dockerfile
      args:
        USER: #leave it empty to use your current user
        UID: ${UID:-1000} # https://docs.docker.com/compose/compose-file/#variable-substitution
        TIME_ZONE: ${TIME_ZONE:-Asia/Ho_Chi_Minh}
        PHP_VER: ${PHP_VER:-7.1}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
    container_name: php71
    volumes:
      - ./public_html/:/var/www/html/
  php82:
    extends:
      service: php
    build:
      args:
        PHP_VER: 8.2
    container_name: php82
#  nodejs:
#    build:
#      context: ./nodejs
#      args:
#        UID: ${UID:-1000}
#    volumes:
#      - ./public_html/:/var/www/html/
#    entrypoint: ["tail", "-f", "/dev/null"]
  httpd:
    build:
      context: ./httpd
    container_name: httpd
    volumes:
      - ./httpd/conf:/usr/local/apache2/conf/docker:ro
      - ./httpd/logs:/usr/local/apache2/logs
      - ./public_html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
  mysql8:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql8
    volumes:
      - ./mysql8/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "1"
    ports:
      - "3306:3306"
